services:
  # Backend API Service
  - type: web
    name: cash-track-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config gunicorn.conf.py app:app"
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FIREBASE_DATABASE_URL
        value: https://cashtrack-182df-default-rtdb.asia-southeast1.firebasedatabase.app
      - key: ALLOWED_ORIGINS
        value: https://cash-track-frontend.onrender.com
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false  # REQUIRED: Download from Firebase Console and set as single-line JSON

  # Frontend Service
  - type: web
    name: cash-track-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://cash-track-backend.onrender.com
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: AIzaSyAZbOv2vN_gz5uop7XxN7AaG3MJv91LRKg
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: cashtrack-182df.firebaseapp.com
      - key: NEXT_PUBLIC_FIREBASE_DATABASE_URL
        value: https://cashtrack-182df-default-rtdb.asia-southeast1.firebasedatabase.app
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: cashtrack-182df
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: cashtrack-182df.firebasestorage.app
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "789777829329"
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: 1:789777829329:web:b1003bc3fe328f8909e4f0
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        value: G-P5DCF2QQ8D