#!/bin/bash

echo "🔥 Firebase Configuration Setup for Cash Track"
echo "============================================="
echo ""
echo "Your app is configured to use Firebase Realtime Database."
echo "For local development, you need to provide Firebase credentials."
echo ""
echo "📋 Steps to configure Firebase:"
echo ""
echo "1. Go to Firebase Console: https://console.firebase.google.com/"
echo "2. Select your project: cashtrack-182df"
echo "3. Go to Project Settings (gear icon) → Service accounts"
echo "4. Click 'Generate new private key'"
echo "5. Download the JSON file"
echo ""
echo "📁 Then choose one of these options:"
echo ""
echo "Option A: Replace the service account file"
echo "   - Replace backend/firebase-service-account.json with your downloaded file"
echo ""
echo "Option B: Use environment variable (recommended)"
echo "   - Copy the JSON content"
echo "   - Add it to backend/.env as FIREBASE_SERVICE_ACCOUNT_JSON='...'"
echo ""
echo "🚀 Your production deployment already has this configured via Render environment variables."
echo ""
echo "Current Firebase Database URL: https://cashtrack-182df-default-rtdb.asia-southeast1.firebasedatabase.app"
echo ""
echo "After configuration, restart the backend server: python3 app.py"